# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PruebaTecnicaBancoAzteca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PruebaTecnicaBancoAzteca
  pod 'Kingfisher'
  pod 'youtube-ios-player-helper'
  target 'PruebaTecnicaBancoAztecaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PruebaTecnicaBancoAztecaUITests' do
    # Pods for testing
  end

end
